# class A:
#     def disp(s,a=0):
#         print(a)

# class B(A):
#     def disp(s,a=0,b=88):
#         print(a,b)

# obj=A()
# obj.disp(2)
# obj=B()
# obj.disp()

# class A:
#     def disp(s,a,b):
#         print(a,b)
# class B:
#     def disp(s,a,d):
#         print(a,b)

# obj=A()
# obj.disp(2,3)  
# obj.disp()   
# obj.disp()   

# class A:
#     def disp(s):
#         print("class a")

# class B:
#     def disp(s):
#         print("class b")

# class C(A,B):
#     def disp(s):
#         print("class c")
#         super().disp()
#         B().disp()

# obj=C()
# obj.disp()
# obj.disp()

# class A:
#     def disp(s):
#         print("class a")

# class B:
#     def disp(s):
#         print("class b")

# obj=A()
# obj.disp()
# obj=B()
# obj.disp()
# obj.disp()




